# Generated by Django 3.0.4 on 2020-03-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fees',
            new_name='Fee',
        ),
    ]
