# Generated by Django 3.0.4 on 2020-03-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0002_auto_20200330_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='standard',
            field=models.IntegerField(unique=True),
        ),
    ]
