# Generated by Django 3.0.4 on 2020-03-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0006_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
