# Generated by Django 3.0.4 on 2020-03-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0007_auto_20200331_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
