# Generated by Django 3.0.4 on 2020-03-31 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0009_cource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cource',
            new_name='Course',
        ),
    ]
