# Generated by Django 3.0.4 on 2020-04-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0012_auto_20200412_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
